"""empty message

Revision ID: 529b7a446cd0
Revises: 27d517f90c2f
Create Date: 2020-04-29 12:07:14.103415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '529b7a446cd0'
down_revision = '27d517f90c2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))

    op.execute('UPDATE todos SET completed = False WHERE completed IS NULL;')
    
    op.alter_column('todos', 'completed', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
