"""empty message

Revision ID: 65577ae1e3a7
Revises: a260ade41d21
Create Date: 2020-04-30 23:52:03.824709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65577ae1e3a7'
down_revision = 'a260ade41d21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
